// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/all-users": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sign-in" | "/dashboard" | "/all-users";
  };
  "routes/root/sign-in.tsx": {
    id: "routes/root/sign-in";
    page: "/sign-in";
  };
  "routes/admin/admin-layout.tsx": {
    id: "routes/admin/admin-layout";
    page: "/dashboard" | "/all-users";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/dashboard";
  };
  "routes/admin/all-users.tsx": {
    id: "routes/admin/all-users";
    page: "/all-users";
  };
};